sudo: false

language: scala

scala:
   - 2.11.12
   - 2.12.10
   - 2.13.1

jdk:
   - oraclejdk9

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

script:
  - sbt clean +test

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
